name = "COESA"
uuid = "13e0c4e3-fd7a-51bf-9e22-ec7679f18909"
authors = ["Daniel Matz <daniel.matz@gmail.com>"]
version = "1.0.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[extras]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
UnitfulExt = ["Unitful"]

[compat]
Unitful = "1"
julia = "1.2"
Requires = "1"
